import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/layout/Sidebar";
import { Toaster } from "sonner";
import { AuthProvider } from "@/context/Auth";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-full">
          <AuthProvider>
            <div className="hidden md:flex h-full w-[72px] z-30 flex-col fixed inset-y-0">
              <Sidebar />
            </div>
            <div className="bg-[#313338] md:pl-[72px] h-screen">
              {children}
              <Toaster
                position="top-right"
                richColors
                closeButton
                duration={2000}
                pauseWhenPageIsHidden
                visibleToasts={1}
              />
            </div>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
