import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "sonner";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <div className=" bg-[#202123] p-4 max-w-xs min-h-screen md:min-w-[20rem]">
            <Sidebar />
          </div>
          <div className="bg-[#313338] flex-1">
            {children}
            <Toaster position="top-right" richColors />
          </div>
        </main>
      </body>
    </html>
  );
}
